<?php

    class Atributos {

        public $attributes = array(
            "eh_homem" => 0,
            "luta" => 0,
            "eh_adulto" => 0,
            "jah_morreu_em_batalha" => 0,
            "eh_do_bem" => 0,
            "nasceu_no_planeta_terra" => 0,
            "teve_filhos" => 0,
            "eh_ou_jah_foi_careca" => 0,
            "utiliza_a_tecnica_kienzan" => 0,
            "eh_companheiro_do_tenshinhan" => 0,
            "pertence_a_raca_sayajin" => 0,
            "utiliza_a_tecnica_kamehameha" => 0,
            "derrotou_o_freeza" => 0,
            "derrotou_o_piccolo" => 0,
            "eh_ou_jah_foi_maligno" => 0,
            "eh_um_principe" => 0,
            "eh_ou_parece_uma_crianca" => 0,
            "eh_mulher" => 0,
            "eh_casada_com_um_sayajin" => 0,
            "eh_cientista" => 0,
            "utiliza_a_tecnica_kikouhouda" => 0,
            "ja_utilizou_a_tecnica_da_fusao" => 0,
            "tem_cabelo_prateado" => 0,
            "ja_veio_do_futuro" => 0,
            "tem_um_irmao_sayajin" => 0,
            "eh_estudioso" => 0,
            "derrotou_o_cell" => 0,
            "exige_que_o_filho_estude" => 0,
            "eh_pervertido" => 0,
            "eh_amigo_do_majinboo" => 0,
            "se_acha_o_campeao_do_planeta" => 0,
            "luta_pela_justica" => 0,
            "eh_gordo" => 0,
            "eh_covarde" => 0,
            "eh_um_androide" => 0,
            "tem_uma_irma_androide" => 0,
            "ama_os_animais" => 0,
            "absorve_pessoas" => 0,
            "parece_com_algum_animal" => 0,
            "eh_rosa" => 0,
            "eh_companheiro_do_yancha" => 0,
            "parece_uma_pelucia" => 0,
            "eh_um_ser_celestial" => 0,
            "realiza_desejos" => 0,
            "gosta_de_destruir_planetas" => 0,
            "possui_antenas_na_cabeca" => 0,
            "lembra_uma_barata" => 0,
            "eh_um_namekuseijin" => 0,
            "tem_poder_de_curar_os_outros" => 0,
            "ja_tentou_dominar_o_universo" => 0,
            "ja_teve_um_exercito" => 0,
            "tem_poder_de_regeneracao" => 0,
            "transforma_as_pessoas_em_doce" => 0,
            "eh_magro" => 0,
            "jah_tentou_dominar_o_universo" => 0,
            "jah_teve_um_exercito" => 0,
            "foi_derrotado_pelo_piccolo" => 0,
            "utiliza_a_tecnica_masenko" => 0,
            "usa_oculos_escuros" => 0
        );

    }

 ?>
